// b_ZKaKO61bDN2-1772642987248/src/views/Publish.vue
<template>
  <div class="publish-page">
    <!-- Page Header -->
    <div class="page-header">
      <h1>发布中心</h1>
      <el-button type="primary" @click="showPublishDialog = true">
        <el-icon><Upload /></el-icon>
        一键发布
      </el-button>
    </div>

    <!-- Stats Row -->
    <div class="publish-stats">
      <div class="pstat-item">
        <div class="pstat-icon" style="background-color: rgba(64,158,255,0.1); color: #409eff">
          <el-icon :size="20"><Clock /></el-icon>
        </div>
        <div class="pstat-info">
          <span class="pstat-value">{{ queueStats.pending }}</span>
          <span class="pstat-label">待发布</span>
        </div>
      </div>
      <div class="pstat-item">
        <div class="pstat-icon" style="background-color: rgba(230,162,60,0.1); color: #e6a23c">
          <el-icon :size="20"><Loading /></el-icon>
        </div>
        <div class="pstat-info">
          <span class="pstat-value">{{ queueStats.running }}</span>
          <span class="pstat-label">发布中</span>
        </div>
      </div>
      <div class="pstat-item">
        <div class="pstat-icon" style="background-color: rgba(103,194,58,0.1); color: #67c23a">
          <el-icon :size="20"><CircleCheck /></el-icon>
        </div>
        <div class="pstat-info">
          <span class="pstat-value">{{ queueStats.success }}</span>
          <span class="pstat-label">已成功</span>
        </div>
      </div>
      <div class="pstat-item">
        <div class="pstat-icon" style="background-color: rgba(245,108,108,0.1); color: #f56c6c">
          <el-icon :size="20"><CircleClose /></el-icon>
        </div>
        <div class="pstat-info">
          <span class="pstat-value">{{ queueStats.failed }}</span>
          <span class="pstat-label">失败</span>
        </div>
      </div>
    </div>

    <!-- Publish Queue -->
    <el-card shadow="never" class="section-card">
      <template #header>
        <div class="card-header">
          <span class="card-title">发布队列 ({{ queue.length }})</span>
          <el-button size="small" @click="handleBatchPublish" :disabled="!hasPending">批量发布</el-button>
        </div>
      </template>
      <el-table :data="queue" stripe>
        <el-table-column prop="title" label="内容标题" min-width="240" />
        <el-table-column prop="platforms" label="目标平台" width="250">
          <template #default="{ row }">
            <div class="platform-tags">
              <el-tag v-for="p in row.platforms" :key="p" size="small" effect="plain" class="platform-tag">
                {{ p }}
              </el-tag>
            </div>
          </template>
        </el-table-column>
        <el-table-column prop="status" label="状态" width="120">
          <template #default="{ row }">
            <el-tag :type="statusType(row.status)" size="small" effect="dark">
              {{ statusLabel(row.status) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="createdAt" label="创建时间" width="160" />
        <el-table-column label="操作" width="180" fixed="right">
          <template #default="{ row }">
            <el-button size="small" link type="primary" @click="handleViewLog(row)">日志</el-button>
            <el-button
              v-if="row.status === 'failed'"
              size="small" link type="warning" @click="handleRetry(row)"
            >
              重试
            </el-button>
            <el-button
              v-if="row.status === 'success' && row.results.length"
              size="small" link type="success" @click="handleViewResult(row)"
            >
              查看
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- Platform Config -->
    <el-card shadow="never" class="section-card">
      <template #header>
        <span class="card-title">平台配置</span>
      </template>
      <el-table :data="platforms" stripe>
        <el-table-column prop="name" label="平台名称" width="200">
          <template #default="{ row }">
            <div class="platform-name-cell">
              <el-icon :size="18"><component :is="row.icon" /></el-icon>
              <span>{{ row.name }}</span>
            </div>
          </template>
        </el-table-column>
        <el-table-column prop="enabled" label="状态" width="120">
          <template #default="{ row }">
            <el-tag :type="row.enabled ? 'success' : 'info'" size="small">
              {{ row.enabled ? '已启用' : '未启用' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" min-width="200">
          <template #default="{ row }">
            <el-switch v-model="row.enabled" style="margin-right: 12px" />
            <el-button size="small" @click="handleConfigPlatform(row)">配置</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- Publish Logs -->
    <el-card shadow="never" class="section-card">
      <template #header>
        <span class="card-title">发布日志</span>
      </template>
      <el-timeline>
        <el-timeline-item
          v-for="log in logs"
          :key="log.id"
          :timestamp="log.timestamp"
          :type="log.type"
          placement="top"
        >
          {{ log.message }}
        </el-timeline-item>
      </el-timeline>
    </el-card>

    <!-- Publish Dialog -->
    <el-dialog v-model="showPublishDialog" title="一键发布" width="520px" destroy-on-close>
      <el-form :model="publishForm" label-width="100px">
        <el-form-item label="选择内容" required>
          <el-select v-model="publishForm.contentId" placeholder="选择要发布的内容" style="width: 100%">
            <el-option
              v-for="c in approvedContents"
              :key="c.id"
              :label="c.title"
              :value="c.id"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="目标平台" required>
          <el-checkbox-group v-model="publishForm.platforms">
            <el-checkbox
              v-for="p in enabledPlatforms"
              :key="p.name"
              :label="p.name"
              :value="p.name"
            >
              {{ p.name }}
            </el-checkbox>
          </el-checkbox-group>
        </el-form-item>
        <el-form-item label="发布时间">
          <el-radio-group v-model="publishForm.timing">
            <el-radio value="now">立即发布</el-radio>
            <el-radio value="scheduled">定时发布</el-radio>
          </el-radio-group>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showPublishDialog = false">取消</el-button>
        <el-button type="primary" @click="handleSubmitPublish">确认发布</el-button>
      </template>
    </el-dialog>

    <!-- Log Detail Dialog -->
    <el-dialog v-model="showLogDialog" title="发布详情" width="520px">
      <template v-if="selectedTask">
        <el-descriptions :column="1" border>
          <el-descriptions-item label="内容">{{ selectedTask.title }}</el-descriptions-item>
          <el-descriptions-item label="平台">
            <el-tag v-for="p in selectedTask.platforms" :key="p" size="small" style="margin-right: 4px">{{ p }}</el-tag>
          </el-descriptions-item>
          <el-descriptions-item label="状态">
            <el-tag :type="statusType(selectedTask.status)" size="small">{{ statusLabel(selectedTask.status) }}</el-tag>
          </el-descriptions-item>
          <el-descriptions-item label="创建时间">{{ selectedTask.createdAt }}</el-descriptions-item>
        </el-descriptions>
        <div v-if="selectedTask.results.length" style="margin-top: 16px">
          <h4 style="margin-bottom: 8px; color: #303133">发布结果</h4>
          <div v-for="r in selectedTask.results" :key="r.platform" class="result-item">
            <el-tag :type="r.status === 'success' ? 'success' : 'danger'" size="small">{{ r.platform }}</el-tag>
            <el-link v-if="r.url" type="primary" :href="r.url" target="_blank">{{ r.url }}</el-link>
            <span v-if="r.error" class="error-text">{{ r.error }}</span>
          </div>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { ElMessage } from 'element-plus'
import { Upload, Clock, Loading, CircleCheck, CircleClose } from '@element-plus/icons-vue'
import { mockPublishQueue, mockPlatforms, mockPublishLogs, mockContents } from '@/api/mock'
import type { PublishTask, Platform, PublishLog } from '@/types/publish'

const queue = ref<PublishTask[]>([...mockPublishQueue])
const platforms = ref<Platform[]>([...mockPlatforms])
const logs = ref<PublishLog[]>([...mockPublishLogs])

const showPublishDialog = ref(false)
const showLogDialog = ref(false)
const selectedTask = ref<PublishTask | null>(null)

const publishForm = ref({
  contentId: null as number | null,
  platforms: [] as string[],
  timing: 'now'
})

const approvedContents = mockContents.filter(c => c.status === 'approved' || c.status === 'published')
const enabledPlatforms = computed(() => platforms.value.filter(p => p.enabled))
const hasPending = computed(() => queue.value.some(q => q.status === 'pending'))

const queueStats = computed(() => ({
  pending: queue.value.filter(q => q.status === 'pending').length,
  running: queue.value.filter(q => q.status === 'running').length,
  success: queue.value.filter(q => q.status === 'success').length,
  failed: queue.value.filter(q => q.status === 'failed').length,
}))

function statusType(status: string) {
  const map: Record<string, string> = {
    pending: 'info',
    running: 'warning',
    success: 'success',
    failed: 'danger'
  }
  return map[status] || 'info'
}

function statusLabel(status: string) {
  const map: Record<string, string> = {
    pending: '待发布',
    running: '发布中',
    success: '已成功',
    failed: '失败'
  }
  return map[status] || status
}

function handleViewLog(task: PublishTask) {
  selectedTask.value = task
  showLogDialog.value = true
}

function handleViewResult(task: PublishTask) {
  selectedTask.value = task
  showLogDialog.value = true
}

function handleRetry(task: PublishTask) {
  const index = queue.value.findIndex(q => q.id === task.id)
  if (index !== -1) {
    queue.value[index] = { ...queue.value[index], status: 'running', results: [] }
    ElMessage.info('正在重新发布...')
    setTimeout(() => {
      queue.value[index] = {
        ...queue.value[index],
        status: 'success',
        results: queue.value[index].platforms.map(p => ({ platform: p, status: 'success' as const, url: `https://${p.toLowerCase()}.com/post/${Date.now()}` }))
      }
      ElMessage.success('发布成功')
    }, 2000)
  }
}

function handleBatchPublish() {
  queue.value = queue.value.map(q =>
    q.status === 'pending' ? { ...q, status: 'running' } : q
  )
  ElMessage.info('批量发布已启动')
}

function handleConfigPlatform(platform: Platform) {
  ElMessage.info(`配置 ${platform.name} 平台（功能开发中）`)
}

function handleSubmitPublish() {
  if (!publishForm.value.contentId || publishForm.value.platforms.length === 0) {
    ElMessage.warning('请选择内容和目标平台')
    return
  }
  const content = approvedContents.find(c => c.id === publishForm.value.contentId)
  const newTask: PublishTask = {
    id: queue.value.length + 1,
    contentId: publishForm.value.contentId,
    title: content?.title || '',
    platforms: publishForm.value.platforms,
    status: 'pending',
    results: [],
    createdAt: new Date().toLocaleString('zh-CN')
  }
  queue.value.unshift(newTask)
  logs.value.unshift({
    id: logs.value.length + 1,
    timestamp: new Date().toLocaleString('zh-CN'),
    type: 'info',
    message: `新增发布任务：${content?.title} -> ${publishForm.value.platforms.join(', ')}`
  })
  showPublishDialog.value = false
  publishForm.value = { contentId: null, platforms: [], timing: 'now' }
  ElMessage.success('发布任务已创建')
}
</script>

<style scoped>
.publish-page {
  max-width: 1400px;
}

.publish-stats {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 16px;
  margin-bottom: 20px;
}

.pstat-item {
  background: #ffffff;
  border: 1px solid #e4e7ed;
  border-radius: 10px;
  padding: 16px 20px;
  display: flex;
  align-items: center;
  gap: 14px;
}

.pstat-icon {
  width: 44px;
  height: 44px;
  border-radius: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.pstat-info {
  display: flex;
  flex-direction: column;
}

.pstat-value {
  font-size: 24px;
  font-weight: 700;
  color: #303133;
}

.pstat-label {
  font-size: 12px;
  color: #909399;
}

.section-card {
  margin-bottom: 20px;
}

.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.card-title {
  font-size: 16px;
  font-weight: 600;
  color: #303133;
}

.platform-tags {
  display: flex;
  gap: 4px;
  flex-wrap: wrap;
}

.platform-name-cell {
  display: flex;
  align-items: center;
  gap: 8px;
  color: #303133;
  font-weight: 500;
}

.result-item {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 0;
  border-bottom: 1px solid #f0f0f0;
}

.result-item:last-child {
  border-bottom: none;
}

.error-text {
  color: #f56c6c;
  font-size: 13px;
}
</style>

// frontend-content-auto-nextv0/app/publish/page.tsx
'use client'

import { useState } from 'react'
import {
  Send,
  RefreshCw,
  ExternalLink,
  CheckCircle2,
  XCircle,
  Clock,
  Loader2,
  Settings2,
} from 'lucide-react'
import { DashboardLayout } from '@/components/dashboard-layout'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Switch } from '@/components/ui/switch'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Checkbox } from '@/components/ui/checkbox'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  mockPublishTasks,
  mockPlatforms,
  mockPublishLogs,
  mockContents,
} from '@/lib/mock-data'
import type { PublishTask } from '@/lib/types'

const taskStatusConfig: Record<PublishTask['status'], { label: string; icon: typeof CheckCircle2; className: string }> = {
  pending: { label: '等待中', icon: Clock, className: 'text-muted-foreground' },
  running: { label: '发布中', icon: Loader2, className: 'text-primary animate-spin' },
  success: { label: '已完成', icon: CheckCircle2, className: 'text-success' },
  failed: { label: '失败', icon: XCircle, className: 'text-destructive' },
}

const logTypeColors: Record<string, string> = {
  success: 'bg-success',
  warning: 'bg-warning',
  danger: 'bg-destructive',
  info: 'bg-primary',
}

export default function PublishPage() {
  const [publishDialogOpen, setPublishDialogOpen] = useState(false)
  const [selectedContent, setSelectedContent] = useState('')
  const [selectedPlatforms, setSelectedPlatforms] = useState<string[]>([])

  const approvedContents = mockContents.filter(
    (c) => c.status === 'approved' || c.status === 'published'
  )

  const handlePublish = () => {
    console.log('Publishing:', selectedContent, selectedPlatforms)
    setPublishDialogOpen(false)
  }

  const togglePlatform = (platform: string) => {
    setSelectedPlatforms((prev) =>
      prev.includes(platform)
        ? prev.filter((p) => p !== platform)
        : [...prev, platform]
    )
  }

  return (
    <DashboardLayout title="发布中心">
      <div className="flex flex-col gap-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex gap-4 text-sm text-muted-foreground">
            <span>队列中 <strong className="text-foreground">{mockPublishTasks.length}</strong> 个任务</span>
            <span>成功 <strong className="text-foreground">{mockPublishTasks.filter(t => t.status === 'success').length}</strong></span>
            <span>失败 <strong className="text-destructive">{mockPublishTasks.filter(t => t.status === 'failed').length}</strong></span>
          </div>
          <Button onClick={() => setPublishDialogOpen(true)}>
            <Send className="mr-1.5 size-4" />
            一键发布
          </Button>
        </div>

        {/* Publish queue */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base">发布队列</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>内容标题</TableHead>
                  <TableHead className="w-[200px]">目标平台</TableHead>
                  <TableHead className="w-[120px]">状态</TableHead>
                  <TableHead className="w-[160px]">创建时间</TableHead>
                  <TableHead className="w-[120px] text-right">操作</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {mockPublishTasks.map((task) => {
                  const statusConfig = taskStatusConfig[task.status]
                  const StatusIcon = statusConfig.icon
                  return (
                    <TableRow key={task.id}>
                      <TableCell className="font-medium text-foreground">
                        {task.contentTitle}
                      </TableCell>
                      <TableCell>
                        <div className="flex flex-wrap gap-1">
                          {task.platforms.map((p) => (
                            <Badge key={p} variant="secondary" className="text-xs">
                              {p}
                            </Badge>
                          ))}
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-1.5">
                          <StatusIcon className={`size-4 ${statusConfig.className}`} />
                          <span className="text-sm">{statusConfig.label}</span>
                        </div>
                      </TableCell>
                      <TableCell className="text-muted-foreground">
                        {task.createdAt}
                      </TableCell>
                      <TableCell>
                        <div className="flex justify-end gap-2">
                          {task.results.some(r => r.url) && (
                            <Button variant="ghost" size="sm">
                              <ExternalLink className="size-3.5" />
                            </Button>
                          )}
                          {task.status === 'failed' && (
                            <Button variant="outline" size="sm">
                              <RefreshCw className="mr-1 size-3.5" />
                              重试
                            </Button>
                          )}
                        </div>
                      </TableCell>
                    </TableRow>
                  )
                })}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
          {/* Platform config */}
          <Card>
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-base">平台配置</CardTitle>
                <Button variant="ghost" size="sm">
                  <Settings2 className="mr-1 size-3.5" />
                  管理
                </Button>
              </div>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col gap-4">
                {mockPlatforms.map((platform) => (
                  <div
                    key={platform.id}
                    className="flex items-center justify-between rounded-lg border bg-card p-3"
                  >
                    <div className="flex items-center gap-3">
                      <div className="flex size-9 items-center justify-center rounded-md bg-muted text-sm font-bold text-muted-foreground">
                        {platform.icon}
                      </div>
                      <div>
                        <p className="text-sm font-medium text-foreground">{platform.name}</p>
                        <p className="text-xs text-muted-foreground">
                          {platform.configured ? '已配置' : '未配置'}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <Badge variant={platform.enabled ? 'default' : 'outline'} className="text-xs">
                        {platform.enabled ? '已启用' : '未启用'}
                      </Badge>
                      <Switch checked={platform.enabled} />
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Publish logs */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">发布日志</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="relative flex flex-col gap-0">
                {mockPublishLogs.map((log, index) => (
                  <div key={log.id} className="flex gap-3 pb-5 last:pb-0">
                    <div className="flex flex-col items-center">
                      <div className={`size-2.5 shrink-0 rounded-full ${logTypeColors[log.type]}`} />
                      {index < mockPublishLogs.length - 1 && (
                        <div className="mt-1 w-px flex-1 bg-border" />
                      )}
                    </div>
                    <div className="flex-1 -mt-0.5">
                      <p className="text-sm leading-relaxed text-foreground">{log.message}</p>
                      <p className="mt-0.5 text-xs text-muted-foreground">{log.timestamp}</p>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Publish dialog */}
      <Dialog open={publishDialogOpen} onOpenChange={setPublishDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>一键发布</DialogTitle>
            <DialogDescription>
              选择要发布的内容和目标平台
            </DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-5 py-4">
            <div className="flex flex-col gap-2">
              <Label>选择内容</Label>
              <Select value={selectedContent} onValueChange={setSelectedContent}>
                <SelectTrigger>
                  <SelectValue placeholder="请选择内容" />
                </SelectTrigger>
                <SelectContent>
                  {approvedContents.map((c) => (
                    <SelectItem key={c.id} value={c.id.toString()}>
                      {c.title}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-3">
              <Label>目标平台</Label>
              {mockPlatforms
                .filter((p) => p.enabled)
                .map((platform) => (
                  <div key={platform.id} className="flex items-center gap-2">
                    <Checkbox
                      id={`platform-${platform.id}`}
                      checked={selectedPlatforms.includes(platform.name)}
                      onCheckedChange={() => togglePlatform(platform.name)}
                    />
                    <Label htmlFor={`platform-${platform.id}`} className="font-normal">
                      {platform.name}
                    </Label>
                  </div>
                ))}
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setPublishDialogOpen(false)}>
              取消
            </Button>
            <Button
              onClick={handlePublish}
              disabled={!selectedContent || selectedPlatforms.length === 0}
            >
              确认发布
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </DashboardLayout>
  )
}
