// frontend-content-auto-nextv0/components/product-card.tsx
'use client'

import { Star } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import type { Product } from '@/lib/types'

const statusMap: Record<Product['status'], { label: string; variant: 'default' | 'secondary' | 'outline' | 'destructive' }> = {
  pending: { label: '待处理', variant: 'outline' },
  researching: { label: '调研中', variant: 'default' },
  covered: { label: '已覆盖', variant: 'secondary' },
  ignored: { label: '已忽略', variant: 'destructive' },
}

export function ProductCard({
  product,
  onViewMaterials,
  onGenerate,
}: {
  product: Product
  onViewMaterials: (product: Product) => void
  onGenerate: (product: Product) => void
}) {
  const status = statusMap[product.status]

  return (
    <Card className="overflow-hidden transition-shadow hover:shadow-md">
      <div className="aspect-square w-full overflow-hidden bg-muted">
        <img
          src={product.imageUrl}
          alt={product.title}
          className="size-full object-cover transition-transform hover:scale-105"
          crossOrigin="anonymous"
        />
      </div>
      <CardContent className="p-4">
        <h3 className="mb-2 line-clamp-2 text-sm font-semibold leading-snug text-foreground">
          {product.title}
        </h3>
        <div className="mb-3 flex items-center gap-3 text-sm text-muted-foreground">
          <span className="font-semibold text-foreground">${product.price}</span>
          <span className="flex items-center gap-1">
            <Star className="size-3.5 fill-warning text-warning" />
            {product.rating}
          </span>
          <span>{product.reviewCount.toLocaleString()} 评论</span>
        </div>
        <div className="mb-3 flex items-center gap-2">
          <Badge variant="outline" className="text-xs">{product.category}</Badge>
          <Badge variant={status.variant} className="text-xs">{status.label}</Badge>
          <Badge variant="secondary" className="ml-auto text-xs">
            潜力 {product.potentialScore}
          </Badge>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            className="flex-1 text-xs"
            onClick={() => onViewMaterials(product)}
          >
            查看素材
          </Button>
          <Button
            size="sm"
            className="flex-1 text-xs"
            onClick={() => onGenerate(product)}
          >
            生成内容
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}

// b_ZKaKO61bDN2-1772642987248/src/components/ProductCard.vue
<template>
  <el-card class="product-card" shadow="hover" :body-style="{ padding: '0' }">
    <div class="card-image-wrapper">
      <el-image :src="product.imageUrl" fit="cover" class="card-image">
        <template #error>
          <div class="image-placeholder">
            <el-icon :size="32"><Picture /></el-icon>
          </div>
        </template>
      </el-image>
      <div class="card-badge">
        <el-tag
          :type="statusMap[product.status]?.type || 'info'"
          size="small"
          effect="dark"
        >
          {{ statusMap[product.status]?.label || product.status }}
        </el-tag>
      </div>
      <div class="potential-score" v-if="product.potentialScore">
        <span class="score-value">{{ product.potentialScore }}</span>
        <span class="score-label">潜力</span>
      </div>
    </div>
    <div class="card-content">
      <h3 class="card-title" :title="product.title">{{ product.title }}</h3>
      <div class="card-meta">
        <span class="price">${{ product.price.toFixed(2) }}</span>
        <div class="rating-info">
          <el-rate
            :model-value="product.rating"
            disabled
            :size="'small'"
            :colors="['#f7ba2a', '#f7ba2a', '#f7ba2a']"
          />
          <span class="review-count">{{ product.reviewCount }} 评论</span>
        </div>
      </div>
      <div class="card-tags">
        <el-tag size="small" type="info" effect="plain">{{ product.category }}</el-tag>
        <el-tag size="small" effect="plain">ASIN: {{ product.asin.slice(0, 6) }}...</el-tag>
      </div>
      <div class="card-actions">
        <el-button size="small" @click="$emit('materials', product)">
          <el-icon><Folder /></el-icon>
          查看素材
        </el-button>
        <el-button size="small" type="primary" @click="$emit('generate', product)">
          <el-icon><MagicStick /></el-icon>
          生成内容
        </el-button>
      </div>
    </div>
  </el-card>
</template>

<script setup lang="ts">
import type { Product } from '@/types/product'
import { Picture, Folder, MagicStick } from '@element-plus/icons-vue'

defineProps<{
  product: Product
}>()

defineEmits<{
  materials: [product: Product]
  generate: [product: Product]
}>()

const statusMap: Record<string, { type: 'success' | 'warning' | 'info' | 'danger'; label: string }> = {
  pending: { type: 'info', label: '待评测' },
  researching: { type: 'warning', label: '研究中' },
  covered: { type: 'success', label: '已覆盖' },
  ignored: { type: 'danger', label: '已忽略' }
}
</script>

<style scoped>
.product-card {
  border-radius: 12px;
  overflow: hidden;
  transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.product-card:hover {
  transform: translateY(-4px);
  box-shadow: 0 12px 24px rgba(0, 0, 0, 0.1);
}

.card-image-wrapper {
  position: relative;
  height: 180px;
  overflow: hidden;
  background-color: #f5f7fa;
}

.card-image {
  width: 100%;
  height: 100%;
}

.image-placeholder {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #f5f7fa;
  color: #c0c4cc;
}

.card-badge {
  position: absolute;
  top: 10px;
  left: 10px;
}

.potential-score {
  position: absolute;
  top: 10px;
  right: 10px;
  background: rgba(0, 0, 0, 0.65);
  border-radius: 8px;
  padding: 4px 10px;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.score-value {
  font-size: 16px;
  font-weight: 700;
  color: #67c23a;
}

.score-label {
  font-size: 10px;
  color: #ffffff;
  opacity: 0.8;
}

.card-content {
  padding: 16px;
}

.card-title {
  font-size: 14px;
  font-weight: 600;
  color: #303133;
  line-height: 1.5;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  margin-bottom: 10px;
}

.card-meta {
  display: flex;
  flex-direction: column;
  gap: 6px;
  margin-bottom: 10px;
}

.price {
  font-size: 20px;
  font-weight: 700;
  color: #409eff;
}

.rating-info {
  display: flex;
  align-items: center;
  gap: 6px;
}

.review-count {
  font-size: 12px;
  color: #909399;
}

.card-tags {
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
  margin-bottom: 12px;
}

.card-actions {
  display: flex;
  gap: 8px;
}

.card-actions .el-button {
  flex: 1;
}
</style>
